version: '3'
services:
  db:
    image: postgres:10.2
  web:
    build: .
    environment:
      DB_HOST: db
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    command: ./run.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
